# Generated by Django 5.0.4 on 2024-04-13 06:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bannersection',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(default='title', max_length=225)),
                ('Bannerimg', models.ImageField(upload_to='uploads/')),
                ('CreatedName', models.CharField(max_length=100)),
                ('Create_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'ordering': ['-Create_at'],
            },
        ),
    ]
